channels:
- metadata:
    CHANNEL_ID: google_play
    MARKET_NAME: Google Play
  name: google_play
- metadata:
    CHANNEL_ID: lizard-android-main
    MARKET_NAME: Main AppGallery
  name: main
output:
  directory: ./channels
  overwrite: true
version: 1.0